# Generated by Django 4.1.7 on 2023-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
